name: Regenerate PluginMaster

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 */12 * * *'

concurrency: regenerate

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
            python-version: '3.8'
            cache: 'pip'

      - name: Generate PluginMaster
        run: |
          pip install -r requirements.txt
          python generate_pluginmaster.py

      - name: Commit PluginMaster
        uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Action
          author_email: github-actions[bot]@users.noreply.github.com
          message: Regenerate PluginMaster