name: Update Dalamud Plugin Repository

on:
  schedule:
    - cron: '0 * * * *' # Run at the start of every hour
  workflow_dispatch: # Allows manual trigger

jobs:
  update-json:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Check for new plugin release and update JSON
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: python .github/scripts/update_json.py

    - name: Commit and push if changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -m "Update Dalamud repository JSON" -a || echo "No changes to commit"
        git push
